#!/usr/bin/env perl

# $Ragnarok$
# Create a sysupdate.

use strict;
use warnings;
use IPC::System::Simple qw(runx);
use POSIX qw(strftime);
use PkgScripts::Emerge qw(emcmd);

my $date	= strftime('%Y%m%d%H%M%S', localtime);
my $dir		= "sysupdate-$date";
my $index	= 'index.txt';

mkdir("$dir");
emcmd("PKGDIR=$dir", '-avuDU', '--with-bdeps=y', '@world');
runx('/usr/bin/tar', 'cpPJvf', "$dir.tar.xz", "$dir");

# Create index.txt if it doesn't already exist
if (! -f $index) {
	open(my $in, '>', $index) or die("Can't open $index for reading: $!\n");
	close($in);
}

open(my $fh, '<', $index) or die("Can't open $index for reading: $!\n");
open(my $tfh, '>', $index.tmp) or die("Can't open $index.tmp file for writing: $!\n");

print($tfh "$dir.tar.xz\n");
while (my $line = <$fh>) {
	print($tfh $line);
}

close($fh) or die("Can't close $index: $!\n");
close($tfh) or die("Can't close $index.tmp: $!\n");

rename("$index.tmp", $index) or die("Can't rename $index.tmp: $!\n");
