.\"	$Ragnarok$
.Dd $Mdocdate$
.Dt PKG_INSTALL 1
.Os
.Sh NAME
.Nm pkg_install
.Nd install or update software packages
.Sh SYNOPSIS
.Nm pkg_install
.Bk -words
.Op Fl p
.Op Fl r
.Op Fl u
.Op Ar pkg-name ...
.Ek
.Sh DESCRIPTION
The
.Nm
command is used to install or update packages from the
.Ar @local
set. In other words,
.Nm
installs and updates packages which are not in the Ragnarok base system
or any of the extra sets.
.Pp
When invoked without any option or
.Ar pkg-name ,
.Nm
will install or update all packages listed in
.Ar @local .
When
.Ar pkg-name
refers to a package already added to the
.Ar @local
set,
.Nm
will simply reinstall the package, whether an update is available or not.
.Pp
The options are as follows:
.Bl -tag -width -Ds
.It Fl p Ar pkg-name
Pretends to install or update a package, or the whole set if no
.Ar pkg-name
is provided, showing what
dependencies would be installed along the way.
.It Fl r Ar pkg-name
Delete/remove
.Ar pkg-name
from the set file. Run
.Xr sysclean 1
afterwards to remove the package from the system.
.It Fl u
If no
.Ar pkg-name
is specified as the second argument, update all packages. Otherwise, update
.Ar pkg-name .
.Sh EMERGE OPTS
.Nm
is merely a wrapper around 
.Xr emerge 1 .
The default emerge options passed are
.Fl avuDU
and 
.Ic \-\-with\-bdeps=y .
This can be changed in the
.Ar pkgscripts.conf
file.
.Sh SEE ALSO
.Xr pkgscripts.conf 5 ,
.Xr emerge 1 ,
.Xr sysclean 1 .

