#!/bin/ksh

# $Ragnarok: pkg_delete,v 1.3 2025/05/10 17:15:23 lecorbeau Exp $
# Remove package from the @local set

set -A _pkgs -- "$@"

# shellcheck disable=SC2154
# Cleanup the set.
for _pkg in "${_pkgs[@]}"; do
	sed -i	-e "s#${_pkg}##g" /etc/portage/sets/local
	sed -i	-e'/^[[:space:]]*$/d' /etc/portage/sets/local
done

# run --depclean against those packages.
/usr/bin/emerge -av --depclean "${_pkgs[@]}"
