#!/bin/ksh

# $Ragnarok: pkg_install,v 1.3 2025/04/16 18:07:42 lecorbeau Exp $
# Install or update "third party" package(s).

# Install packages.
inst_pkg() {
	local _pkgs

	set -A _pkgs -- "$@"

	# It's possible to just install the whole @custom set in one go.
	#if [[ ${#_pkgs[@]} == 0 ]]; then
	if [[ ${_pkgs[*]} == @custom ]]; then
    		/usr/bin/emerge -av --oneshot @custom
	else
		for _pkg in "${_pkgs[@]}"; do
			if ! grep -q "${_pkg}" /etc/portage/sets/custom; then
				printf '%s\n' "$_pkg" >> /etc/portage/sets/custom
			fi
		done

		emerge -av --oneshot --pretend "${_pkgs[@]}"
	fi
}

# Update pkgs.
upd_pkg() {
	/usr/bin/emerge -avuDN --with-bdeps=y --oneshot @custom
}

case "$1" in
	-u)	upd_pkg
		;;
	*)	inst_pkg "$@"
		;;
esac
