#!/usr/bin/env perl

# $Ragnarok$
# pkg_install: install or update non-base system packages.

use strict;
use warnings;

my $pkgs	= @ARGV;

# Add pkg to @local set if it's not already there
sub add_to_set {
	my ($pkg)	= @ARGV;
	my $set		= '/etc/portage/sets/local';

	open(my $fh, '<', $set) or die("Can't open $set file: $!\n");
	my $exists	= 0;
	while(my $line = <$fh>) {
		if ($line =~ /\Q$pkg\E/) {
			$exists = 1;
			last;
		}
	}
	close($fh) or die("Can't close $set file: $!\n");

	if ($exists) {
		print("$pkg is already in $set file, reinstalling...\n");
	} else {
		open($fh, '>>', $set) or die("Can't add $pkg to $set\n");
		print("$fh $pkg\n");
		close($fh) or die("Can't close $set file: $!\n");
	}
}

sub install_pkg {
	foreach my $pkg (@pkgs) {
		add_to_set($pkg);
	}
	system('/usr/bin/emerge', '-avuDU', '--with-bdeps=y', '--oneshot', "$pkgs") == 0
		or die("Can't install $pkgs: $!\n");
}
