#!/usr/bin/env perl

use strict;
use warnings;
use File::Basename;
use IPC::System::Simple qw(capturex);

my ($dir)	= @ARGV;
my @extensions	= qw(.txt .ebuild metadata.xml);

opendir(my $d, $dir) or die("Can't open $dir\n");

while (my $file = readdir($d)) {
	if($file =~ /\.txt$/i || $file =~ /\.ebuild$/i || $file eq 'metadata.xml') {
		my $sum = capturex('/usr/bin/sha256sum', '--tag', "$file");
		print("SHA256: $sum")
	}
}

closedir($d) or die("Can't close $dir\n");
