#!/usr/bin/env perl

# $Ragnarok: getvar,v 1.3 2025/04/30 22:43:21 lecorbeau Exp $
# Read a config value from config file.

use strict;
use warnings;
use Config::Tiny;

my ($section, $value, $conffile) = @ARGV;

# Get values for the Ragnarok repo (default)
my $config	= Config::Tiny->read($conffile);

print("$config->{$section}->{$value}\n")
	or die("Can't get config value: $!\n");
