#!/usr/bin/env perl

# $Ragnarok: getvar,v 1.4 2025/06/17 15:29:18 lecorbeau Exp $
# Read a config value from config file.

use strict;
use warnings;
use Config::General;

my $value = $ARGV[0];

my $conf	= Config::General->new(
	-ConfigFile		=> 'sysupdate.conf',
	-SplitPolicy		=> 'equalsign',
	-InterPolateVars	=> 1
);

my %config = $conf->getall;
print("$config{$value}\n");
