#!/bin/ksh

_TMP="$1"

unpriv() {
	local _file=$3 _ret=0 _user=sysupdate

	if [[ $2 == -f && -n ${_file} ]]; then
		# shellcheck disable=SC2188
		>${_file}
		chown "${_user}" "${_file}"
		chmod 0711 "${_TMP}"
		shift 3
	fi
	(($# >= 2))

	su -s /bin/sh ${_user} -c "$@" || _ret=$?

	[[ -n ${_file} ]] && chown root "${_file}"

	return ${_ret}
}
unpriv "$@"
